services:
  target:
    image: postgres
    environment:
      - POSTGRES_USER=target
      - POSTGRES_PASSWORD=target
      - POSTGRES_DB=target
    ports:
      - "5433:5432"
  symds_target:
    image: jumpmind/symmetricds-pro:3.15.12
    environment:
      - HTTPS=FALSE
      - GROUP_ID=target
      - DB_HOST=target
      - DB_SSL=FALSE
      - DB_TYPE=postgres
      - DB_NAME=target
      - DB_USER=target
      - DB_PASS=target
      - SYNC_URL=http://symds_target:31415/sync/target
      - REGISTRATION_URL=http://symds_source:31415/sync/source
    ports:
      - "31425"
      - "31427"
  symds_source:
    image: jumpmind/symmetricds-pro:3.15.12
    environment:
      - HTTPS=FALSE
      - GROUP_ID=source
      - DB_HOST=source
      - DB_SSL=FALSE
      - DB_TYPE=postgres
      - DB_NAME=source
      - DB_USER=source
      - DB_PASS=source
      - SYNC_URL=http://symds_source:31415/sync/source
      - REPLICATE_TO=target
      - REPLICATE_TABLES=test other_table|name
    ports:
      - "31415:31415"
      - "31417"
  source:
    build:
      context: postgres-source
    environment:
      - POSTGRES_USER=source
      - POSTGRES_PASSWORD=source
      - POSTGRES_DB=source
    ports:
      - "5431:5432"